#!/usr/bin/env python3
import csv
import random
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "question-bank-reference-navigation.tsv"

random.seed(271986)

ROWS = [
    {
        "question": "What became expected to sound when the stop control is opened on equipment installed under the 1980 supplement and later?",
        "answer": "audible signaling device",
        "traps": ["in-car stop switch", "perforated car enclosure", "photoelectric reopening device"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "stop switch signaling",
    },
    {
        "question": "Which passenger-car control replaced the older emergency stop switch expectation on later nonperforated passenger cars?",
        "answer": "in-car stop switch",
        "traps": ["emergency stop switch", "audible signaling device", "perforated enclosure"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "in-car stop switch",
    },
    {
        "question": "For passenger elevators installed under the 1986 supplement and later, what control is required instead of an in-car emergency stop switch?",
        "answer": "key-operated or locked-panel in-car stop switch",
        "traps": ["red emergency stop switch at each landing", "audible alarm only", "photoelectric reopening device"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "later passenger stop controls",
    },
    {
        "question": "On which installations did the stop switch also become expected to activate an audible signaling device?",
        "answer": "1980 supplement and later",
        "traps": ["1975 edition and later", "1982 supplement and later", "1986 supplement and later"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "audible signaling date",
    },
    {
        "question": "On which installations was the emergency stop control required to be in or adjacent to each car operating panel?",
        "answer": "1982 supplement and later",
        "traps": ["1971 edition and later", "1980 supplement and later", "1986 supplement and later"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "car operating panel stop switch",
    },
    {
        "question": "Which elevator type still calls for an emergency stop switch rather than only an in-car stop switch?",
        "answer": "freight elevator",
        "traps": ["nonperforated passenger elevator", "private residence elevator", "escalator"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "freight stop switches",
    },
    {
        "question": "Which existing passenger-car enclosure condition points to an emergency stop switch requirement?",
        "answer": "perforated enclosure",
        "traps": ["nonperforated enclosure", "glass car door", "center-opening entrance"],
        "book": "ASME A17.2-2010",
        "part": "1.2.1",
        "topic": "perforated enclosure stop switch",
    },
    {
        "question": "When checking a safety edge, what result should occur as the car and landing doors are closing?",
        "answer": "doors stop and reopen",
        "traps": ["doors close at reduced speed", "audible signal sounds only", "car returns to recall level"],
        "book": "ASME A17.2-2010",
        "part": "1.1.1",
        "topic": "mechanical reopening device",
    },
    {
        "question": "For vertically sliding car doors or gates, where is a stop-and-reopen response not required for an obstruction?",
        "answer": "near the sides of the opening",
        "traps": ["at the center of the sill", "at the car operating panel", "at the machine-room entrance"],
        "book": "ASME A17.2-2010",
        "part": "1.1.1",
        "topic": "vertical door obstruction exception",
    },
    {
        "question": "A reopening system must detect an obstruction along which part of the car entrance?",
        "answer": "leading edge of the car door",
        "traps": ["car-top railing", "hoistway separator beam", "pit access door"],
        "book": "ASME A17.2-2010",
        "part": "1.1.1",
        "topic": "photoelectric reopening device",
    },
    {
        "question": "When a required car emergency signal is operated and no attendant is continuously available, what additional capability is needed?",
        "answer": "communication or signaling to a responsive service",
        "traps": ["automatic door reopening only", "machine-room fire extinguisher", "pit stop switch"],
        "book": "NYC Appendix K",
        "part": "3.11.1",
        "topic": "emergency communication",
    },
    {
        "question": "Where must the basic audible emergency signal be heard?",
        "answer": "inside the car and outside the hoistway",
        "traps": ["only in the machine room", "only at the fire command station", "only at the top landing"],
        "book": "NYC Appendix K",
        "part": "3.11.1",
        "topic": "audible emergency signal",
    },
    {
        "question": "What switch marking is associated with operating the car emergency signaling device from the car operating panel area?",
        "answer": "ALARM",
        "traps": ["FIREMAN SERVICE", "HOSPITAL EMERGENCY SERVICE", "ENABLE"],
        "book": "NYC Appendix K",
        "part": "3.11.1",
        "topic": "alarm switch marking",
    },
    {
        "question": "What color must the operating handle or button have on the car emergency stop control?",
        "answer": "red",
        "traps": ["green", "yellow", "white"],
        "book": "NYC Appendix K",
        "part": "2.26.2.5",
        "topic": "emergency stop switch marking",
    },
    {
        "question": "When the car emergency stop control is opened, what equipment must lose power?",
        "answer": "driving-machine motor and brake",
        "traps": ["car lighting and alarm bell", "door reopening device only", "fire recall switch only"],
        "book": "NYC Appendix K",
        "part": "2.26.2.5",
        "topic": "emergency stop switch effect",
    },
    {
        "question": "Which labels or positions must be clear on the car emergency stop control?",
        "answer": "STOP and RUN",
        "traps": ["OPEN and CLOSE", "UP and DOWN", "AUTO and MANUAL"],
        "book": "NYC Appendix K",
        "part": "2.26.2.5",
        "topic": "emergency stop switch positions",
    },
    {
        "question": "What lettering is required on a separate pit access door?",
        "answer": "DANGER, ELEVATOR PIT",
        "traps": ["ELEVATOR MACHINE ROOM", "FIRE RECALL", "NO STORAGE"],
        "book": "NYC Appendix K",
        "part": "2.2.4.4",
        "topic": "pit door label",
    },
    {
        "question": "What must be marked on access doors to machine rooms and overhead machinery spaces?",
        "answer": "ELEVATOR MACHINE ROOM",
        "traps": ["DANGER, ELEVATOR PIT", "FIRE RECALL", "CAR TOP ACCESS"],
        "book": "NYC Appendix K",
        "part": "2.7.3.4.1",
        "topic": "machine room door label",
    },
    {
        "question": "What receptacle rating is required in each machine room and machinery space?",
        "answer": "twenty ampere, one hundred twenty volt, GFCI",
        "traps": ["fifteen ampere, one hundred twenty volt, non-GFCI", "twenty ampere, two hundred eight volt only", "thirty ampere disconnect only"],
        "book": "NYC Appendix K",
        "part": "2.7.5.3",
        "topic": "machine room receptacle",
    },
    {
        "question": "What use is prohibited for the required machine-room convenience receptacle?",
        "answer": "permanently installed equipment",
        "traps": ["temporary test equipment", "inspection light", "portable meter"],
        "book": "NYC Appendix K",
        "part": "2.7.5.3",
        "topic": "machine room receptacle use",
    },
    {
        "question": "What communication path is required among the car, equipment area, and fire command station when applicable?",
        "answer": "permanent two-way voice communication",
        "traps": ["single-stroke alarm bell", "visual signal only", "manual hand signal"],
        "book": "NYC Appendix K",
        "part": "2.7.8.4",
        "topic": "two-way communication",
    },
    {
        "question": "Which system is not permitted in control or machine rooms under the modified rule?",
        "answer": "sprinkler system",
        "traps": ["two-way voice communication", "GFCI receptacle", "machine-room lighting"],
        "book": "NYC Appendix K",
        "part": "2.8.2.3",
        "topic": "machine room sprinkler prohibition",
    },
    {
        "question": "What minimum entrance height applies to hoistway landing openings under the modified rule?",
        "answer": "eighty inches",
        "traps": ["seventy-two inches", "eighty-four inches", "ninety-six inches"],
        "book": "NYC Appendix K",
        "part": "2.11.1.1",
        "topic": "hoistway entrance height",
    },
    {
        "question": "What minimum entrance width applies to hoistway landing openings under the modified rule?",
        "answer": "thirty-six inches",
        "traps": ["twenty-four inches", "thirty inches", "forty-two inches"],
        "book": "NYC Appendix K",
        "part": "2.11.1.1",
        "topic": "hoistway entrance width",
    },
    {
        "question": "In a single blind hoistway, how often must emergency doors occur in the blind portion?",
        "answer": "every third floor and within the maximum sill-to-sill spacing",
        "traps": ["only at the top terminal landing", "every floor regardless of spacing", "only where a sprinkler is installed"],
        "book": "NYC Appendix K",
        "part": "2.11.1.2",
        "topic": "blind hoistway emergency doors",
    },
    {
        "question": "Which passenger entrance type is included among the permitted passenger-elevator entrance types?",
        "answer": "horizontally sliding",
        "traps": ["vertically sliding biparting counterbalanced", "center-opening two-panel swinging", "perforated collapsible gate only"],
        "book": "NYC Appendix K",
        "part": "2.11.2.1",
        "topic": "passenger entrance type",
    },
    {
        "question": "Which freight entrance type is included among the permitted freight-elevator entrance types?",
        "answer": "vertically sliding biparting counterbalanced",
        "traps": ["sidewalk elevator cover", "glass-only sliding panel", "zero-clearance vestibule door"],
        "book": "NYC Appendix K",
        "part": "2.11.2.2",
        "topic": "freight entrance type",
    },
    {
        "question": "Where is locking a hoistway door out of service not permitted?",
        "answer": "top terminal landing",
        "traps": ["nonterminal tenant floor only", "machine-room door", "pit access door"],
        "book": "NYC Appendix K",
        "part": "2.11.6.2",
        "topic": "door lockout limitation",
    },
    {
        "question": "Which lobby condition permits a very small vestibule only when the required locking arrangement is accessible from the car?",
        "answer": "zero-clearance vestibule",
        "traps": ["sky lobby", "blind hoistway", "machine room"],
        "book": "NYC Appendix K",
        "part": "2.11.6.5",
        "topic": "zero-clearance vestibule",
    },
    {
        "question": "What protective material may be required over hoistway-door vision panels?",
        "answer": "metal protective grills",
        "traps": ["wood trim", "plastic warning tape", "smoke baffles"],
        "book": "NYC Appendix K",
        "part": "2.11.7.1.2.1",
        "topic": "vision panel guards",
    },
    {
        "question": "What is the largest ball that protective vision-panel grill openings must reject?",
        "answer": "three-quarter inch ball",
        "traps": ["one-quarter inch ball", "one-and-one-half inch ball", "four inch ball"],
        "book": "NYC Appendix K",
        "part": "2.11.7.1.2.1",
        "topic": "vision panel grill opening",
    },
    {
        "question": "Which service is tied to patient transport in a life-or-death situation?",
        "answer": "hospital emergency service",
        "traps": ["firefighters service", "standby power operation", "inspection operation"],
        "book": "NYC Appendix K",
        "part": "1.3",
        "topic": "hospital emergency service",
    },
    {
        "question": "Which elevator is reserved for nonambulatory patients incapable of self-preservation?",
        "answer": "patient elevator",
        "traps": ["freight elevator", "material lift", "sidewalk elevator"],
        "book": "NYC Appendix K",
        "part": "1.3",
        "topic": "patient elevator",
    },
    {
        "question": "What term describes the lowest landing of a group of elevators above street level?",
        "answer": "sky lobby",
        "traps": ["designated level", "zero-clearance vestibule", "blind hoistway"],
        "book": "NYC Appendix K",
        "part": "1.3",
        "topic": "sky lobby",
    },
    {
        "question": "What term describes the opening used for venting at the top of elevator hoistways?",
        "answer": "smoke hole",
        "traps": ["sky lobby", "refuge space", "separator beam"],
        "book": "NYC Appendix K",
        "part": "1.3",
        "topic": "smoke hole",
    },
    {
        "question": "What slope angle is used as the threshold for beveling certain hoistway projections?",
        "answer": "seventy-five degrees",
        "traps": ["forty-five degrees", "sixty degrees", "ninety degrees"],
        "book": "NYC Appendix K",
        "part": "2.1.6.2",
        "topic": "hoistway projection bevel",
    },
    {
        "question": "What must be provided where elevators have sprinklers in the shaftway?",
        "answer": "drain or sump pump",
        "traps": ["zero-clearance vestibule", "smoke hole", "separate machine room"],
        "book": "NYC Appendix K",
        "part": "2.2.2.5",
        "topic": "shaftway sprinkler drainage",
    },
    {
        "question": "What must top-of-car portable inspection equipment include if it is used to reach the farthest corner?",
        "answer": "enable device and stop switch",
        "traps": ["alarm bell and fire recall switch", "door restrictor and vision panel", "governor seal and data plate"],
        "book": "NYC Appendix K",
        "part": "2.26.1.4",
        "topic": "portable inspection unit",
    },
    {
        "question": "During Phase II service, which switch positions are used on the in-car firefighter control?",
        "answer": "NORMAL, HOLD, and FIREMAN SERVICE",
        "traps": ["STOP, RUN, and TEST", "UP, DOWN, and INSPECTION", "AUTO, MANUAL, and BYPASS"],
        "book": "NYC Appendix K",
        "part": "2.27.3.3",
        "topic": "phase ii switch positions",
    },
    {
        "question": "When Phase II is active, who controls car operation?",
        "answer": "designated person in the car",
        "traps": ["building attendant at the lobby only", "automatic group controller only", "machine-room mechanic only"],
        "book": "NYC Appendix K",
        "part": "2.27.3.3.1",
        "topic": "phase ii car control",
    },
    {
        "question": "Which operating mode is used to recall patient elevators to the call landing?",
        "answer": "hospital emergency service recall operation",
        "traps": ["occupant evacuation operation", "inspection operation", "normal automatic operation"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "hospital recall",
    },
    {
        "question": "After hospital emergency in-car operation is activated, which person controls the patient elevator from the car?",
        "answer": "designated person",
        "traps": ["fire alarm dispatcher", "building tenant", "outside elevator passenger"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.2",
        "topic": "hospital in-car control",
    },
    {
        "question": "How long must a hospital emergency service audible signal operate before manual silencing is permitted?",
        "answer": "at least five seconds",
        "traps": ["until the next inspection", "at least thirty seconds", "only while the stop switch is open"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3",
        "topic": "hospital audible signal",
    },
    {
        "question": "What color is associated with the escalator emergency stop button?",
        "answer": "red",
        "traps": ["green", "blue", "white"],
        "book": "NYC Appendix K",
        "part": "5.3.2",
        "topic": "escalator stop button",
    },
    {
        "question": "Where are escalator emergency stop buttons required to be visibly located?",
        "answer": "top and bottom landings",
        "traps": ["machine room only", "center of the truss only", "inside the controller cabinet only"],
        "book": "NYC Appendix K",
        "part": "5.3.2",
        "topic": "escalator stop button location",
    },
    {
        "question": "What type of escalator stop buttons are generally prohibited except for fire-alarm-connected gradual stopping?",
        "answer": "remote stop buttons",
        "traps": ["red landing stop buttons", "comb-step stop devices", "skirt obstruction devices"],
        "book": "NYC Appendix K",
        "part": "5.3.2",
        "topic": "remote escalator stop buttons",
    },
    {
        "question": "What device must stop an escalator before an object reaches the combplate?",
        "answer": "skirt obstruction device",
        "traps": ["speed governor", "car emergency signal", "pit stop switch"],
        "book": "NYC Appendix K",
        "part": "5.3.7",
        "topic": "skirt obstruction protection",
    },
    {
        "question": "What device opens the power circuit to the escalator driving machine when the comb-step condition occurs?",
        "answer": "comb-step stop device",
        "traps": ["governor overspeed switch", "hospital recall switch", "car-top inspection station"],
        "book": "NYC Appendix K",
        "part": "5.3.12",
        "topic": "comb-step stop device",
    },
    {
        "question": "What must a conveyor enclosure opening reject when grille or perforated material is used?",
        "answer": "one-and-one-half inch ball",
        "traps": ["three-quarter inch ball", "four inch ball", "six inch ball"],
        "book": "NYC Appendix K",
        "part": "6.3.4",
        "topic": "perforated conveyor enclosure",
    },
    {
        "question": "What minimum clear height is identified for conveyor enclosure walls?",
        "answer": "eighty inches",
        "traps": ["sixty inches", "seventy-two inches", "ninety-six inches"],
        "book": "NYC Appendix K",
        "part": "6.3.4",
        "topic": "conveyor enclosure height",
    },
    {
        "question": "Which material type may be used for conveyor enclosure walls along with solid and grille construction?",
        "answer": "perforated material",
        "traps": ["tempered glass only", "canvas curtain", "open chain only"],
        "book": "NYC Appendix K",
        "part": "6.3.4",
        "topic": "conveyor enclosure material",
    },
    {
        "question": "For moving walks, where are red emergency stop buttons required to be visibly located?",
        "answer": "top and bottom landings",
        "traps": ["inside the machine room only", "at every pallet only", "at the fire command station only"],
        "book": "NYC Appendix K",
        "part": "9.6.3",
        "topic": "moving walk stop button location",
    },
    {
        "question": "What moving-walk device is the counterpart to the escalator comb-step stop device?",
        "answer": "comb-pallet stop device",
        "traps": ["skirt obstruction device", "patient elevator recall switch", "pit stop switch"],
        "book": "NYC Appendix K",
        "part": "9.6.12",
        "topic": "comb-pallet stop device",
    },
    {
        "question": "For passenger elevators and freight elevators, which component must be tested to hold the required load?",
        "answer": "brake",
        "traps": ["alarm switch", "vision panel grill", "pit ladder"],
        "book": "NYC Appendix K",
        "part": "8.11.2.3.4",
        "topic": "braking system",
    },
    {
        "question": "Which normal service feature must be overridden by hospital emergency recall?",
        "answer": "normal automatic operating modes",
        "traps": ["pit lighting circuit", "hoistway-door vision panel", "machine-room receptacle"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "hospital recall priority",
    },
    {
        "question": "What happens to a patient elevator traveling away from the hospital emergency call landing?",
        "answer": "it reverses at or before the next available landing",
        "traps": ["it continues to the original registered call", "it shuts down in the hoistway", "it opens immediately between floors"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "hospital recall travel response",
    },
    {
        "question": "What signal must alert passengers or attendants during patient elevator recall?",
        "answer": "visual and audible signal",
        "traps": ["pit buzzer only", "machine-room light only", "door reopening chime only"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "patient elevator recall signal",
    },
    {
        "question": "What must happen if Phase I recall starts before in-car hospital service is activated?",
        "answer": "the elevator reverts to Phase I",
        "traps": ["the car remains on hospital recall", "the pit switch bypasses recall", "the alarm switch disables the doors"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "hospital service and phase i",
    },
    {
        "question": "Which key-operated patient-elevator switch positions are used for in-car hospital emergency service?",
        "answer": "NORMAL and HOSPITAL EMERGENCY SERVICE",
        "traps": ["STOP and RUN", "UP and DOWN", "AUTO and BYPASS"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.2",
        "topic": "hospital in-car switch positions",
    },
    {
        "question": "What is the inspection concern when a car is standing with doors open on patient recall and the stop control is in run?",
        "answer": "doors close without delay and the car proceeds to the designated level",
        "traps": ["doors remain open until manually reset", "car shuts down at the landing", "machine-room sprinkler activates"],
        "book": "NYC Appendix K",
        "part": "2.27.5.3.1",
        "topic": "patient recall doors",
    },
]


def write_rows():
    letters = ["A", "B", "C", "D"]
    rows = []
    for idx, item in enumerate(ROWS, start=1):
        options = item["traps"] + [item["answer"]]
        random.shuffle(options)
        correct = letters[options.index(item["answer"])]
        rows.append([
            idx,
            item["question"],
            options[0],
            options[1],
            options[2],
            options[3],
            correct,
            item["book"],
            item["part"],
            item["topic"],
            "requirement_interpretation",
        ])
    with OUT.open("w", newline="") as file:
        writer = csv.writer(file, delimiter="\t", lineterminator="\n")
        writer.writerows(rows)
    print(f"wrote {OUT}")
    print(f"rows={len(rows)}")


if __name__ == "__main__":
    write_rows()
